- libsql/internal/http/driver.go
- libsql/internal/http/http.go
Though the `ExecContext` and `QueryContext` take ctx parameter, they were not using them. This PR, makes these methods to pass them to `callSqld` method, which can be used in http calls.
E.g. if a user wants to cancel the operation if it isn't completed in under 1 second, the code would be:
```go
ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
defer cancel()
res, err := db.QueryContext(ctx, stmt, args...)
```
> Pass ctx down to http calls

- libsql/internal/http/http.go
- libsql/internal/ws/driver.go
- libsql/internal/ws/websockets.go
This PR, makes the internal methods to pass ctx to websocket library. 
- Updated `ExecContext` and `QueryContext`, they will pass the ctx down
- In the connect call, a new ctx with timeout is created and is passed to `wsjson`
- I have done same in `Exec` and `Query` methods too.
Also, taking from the discussion https://github.com/libsql/libsql-client-go/issues/9#issuecomment-1511408276 I have added timeout of 120 seconds to both websocket and http calls.
> Pass ctx down to websocket calls

- libsql/internal/ws/websockets.go
libsql uses base64 without padding (char '=') to return blob values
References:
https://en.wikipedia.org/wiki/Base64#Output_padding
https://pkg.go.dev/encoding/base64#Encoding.WithPadding
> Fix: libsql uses base64 without padding (char '=') to return blob values

- libsql/sql.go
This parameter can be used to opt out of TLS when using `libsql:` URL. It is also possible to use it with HTTP and WebSocket URLs, but in this case we just check that it matches the existing scheme (i.e., `https://localhost?tls=0` throws an error). We also require every `libsql:` URL with `?tls=0` to specify an explicit port, because the default port for `libsql:` URL is 443, which could produce unexpected results.
If the URL contains unsupported query parameters, we now return an error. This provides compatibility with other clients and makes it easier for users to debug issues.
This also makes sure that we don't send the parsed query parameters (such as the auth token) to the server. The code apparently attempted to do so by calling `url.Query().Del()`, but this modifies only a …
> Add support for ?tls=0 query parameter

- README.md
Removed the part about running the examples because they seem to be out of date and don't work without modifications.
> Add basic documentation to README

- libsql/sql.go
Addressing #37 
- Added check if the file schema URL has double leading slash
- Added an appropriate error message on such file URLs
Please let me know if it is a valid fix, or if I need to make changes further.
Thank you.
> fix file url with double slash error message

- libsql/internal/hrana/stream_request.go
- tests/http/driver_test.go
The following code does not work on the main branch: https://gist.github.com/rylev/b28e503d33b3dbf7f45843903cb3da3a.
This fixes the very subtle bug where by the last statement was being repeatedly referenced instead of each statement being referenced individually. 
I've added a test to prevent regressions.
> Ensure multi-line statements work

- libsql/internal/hrana/value.go
- libsql/internal/hrana/value_test.go
Hrana returns integers as strings. We need to parse it while creating `drive.Value`
> fix: hrana Value passing integers as strings and add tests to it

- .github/workflows/go.yml
- tests/http/driver_test.go
- tests/ws/driver_test.go
we have protocol specific tests in `tests/`, however both `tests/http` and `tests/ws` were using same protocol `http` since we set a single environment variable and use the same at both places. I changed it to protocol specific ones to make it explicit and updated the correct URLs at both places
> bugfix: run tests according to protocol

- libsql/internal/http/hranaV2/hranaV2.go
> Reset baton when connection is returned to the pool

- libsql/internal/http/hranaV2/hranaV2.go
If the server returns 401, for example, it is *not* in the same format as Hrana errors. Therefore, first attempt to parse a server error and only then parse Hrana errors.
For example, the following error:
Error: failed to connect to database. err: failed to execute SQL: SELECT 1;
now becomes:
Error: failed to connect to database. err: failed to execute SQL: SELECT 1;
error code 401: Unauthorized: `The `Authorization` HTTP header is required but was not specified`
> Fix server error handling

- libsql/internal/hrana/value.go
- libsql/internal/hrana/value_test.go
This PR fixes scanning for a Boolean type and also detecting a `TIMESTAMP` as it comes in from a column of a query.
> Fix boolean scan and detect TIMESTAMP type

- libsql/internal/http/hranaV2/hranaV2.go
Instead mark connection as `closeStreamOnNextRequest` and prepend `StreamClose` request to the pipeline before the next request.
Fixes #84
> Improve ResetSession by not sending requests

- libsql/internal/hrana/value.go
For me these values are lowercase. I'm unsure when they are upper case, but this fixes it so the comparison is always lowercase, without this I was hitting unsupported scan errors. Also everything else happens to be lowercase as well, so I'm unsure if the `strings.ToLower` is required, but I put it there just in case the values can be all caps.
> fix: always check against lowercase

- libsql/internal/http/hranaV2/hranaV2.go
Closes: https://github.com/tursodatabase/libsql/issues/770
Reported here: https://github.com/pressly/goose/issues/655#issuecomment-1847454551
Since we pass around the URL string, in case of trailing slash, the final URL ended up being: `https://mydb-avinassh.turso.io//v2/pipeline`
> bugfix: handle trailing slash in the request URL

- .github/workflows/go.yml
- go.mod
- libsql/sql.go
Goose is a pretty slick migration tool and I am trying to add Turso support to it. I have opened a PR here - https://github.com/pressly/goose/pull/658
However, goose minimum go version requirement is 1.19 and maintainers do not want to increase it to 1.21 just for Turso, which is reasonable. But they are fine merging if the version is 1.20.
In our library, we only use `slice.Contains` function, so I have back ported those and reduced the min version to 1.20
> Downgrade Go version to 1.20

- examples/sql/counter/main.go
- libsql/internal/http/hranaV2/hranaV2.go
- libsql/internal/ws/driver.go
- tests/http/driver_test.go
- tests/ws/driver_test.go
This PR adds a Ping and PingContext method to the Driver which satisfy the sql driver interface.
It uses a simple SELECT 1 to test the connection, which I believe is how most drivers implement a ping.
I have added a test to test the funcitonality and also included an example.
Closes #96
> feat: Add ping ability

- libsql/internal/hrana/value.go
- libsql/internal/hrana/value_test.go
While trying to insert an empty slice in a blob, I kept getting the same error;
```
missing field `base64`
```
While reading the library code, I noticed that if Base64 was and empty string `""`, due to `omitempty`, it was not marshalled.
Which caused the issue.
---
The fix is to simply make Base64 into a pointer. That means for the blob type, the pointer will not be `nil` and will be marshalled.
> Value Base64 should be a pointer to allow empty blobs

- libsql/internal/ws/websockets.go
- libsql/internal/ws/websockets_test.go
This adds support for passing down bool in queries.
```go
db.ExecContext(ctx, "INSERT INTO people (id, cool_guy) VALUES (?, ?)", 1, true)
db.ExecContext(ctx, "INSERT INTO people (id, cool_guy) VALUES (?, ?)", 1, false)
```
previously it would spit out a error. "unsupported value type: %!s(bool=false) (string)"
> add support for boolean in ws stmt arguments payload

- libsql/internal/hrana/stream_request.go
- libsql/internal/http/driver.go
- libsql/internal/http/hranaV2/hranaV2.go
- libsql/sql.go
Schema migrations fail if they consist a transaction so we need to make sure that a batch sent to a schema db is not transactional. Otherwise the operation fails with:
```
Schema migration error: migration is invalid: it contains transaction items (BEGIN, COMMIT, SAVEPOINT...) which are not allowed. The migration is already run within a transaction
```
> Make it possible to signal to the driver that we're connecting to schema db and use nontransactional batches in such case

- libsql/internal/http/hranaV2/hranaV2.go
- sqliteparserutils/utils.go
This fixes two things.
1. SQLD was just going OOM when the batch was too big
2. Client memory usage was very high
> Execute big batches in smaller chunks

- libsql/internal/http/hranaV2/hranaV2.go
Callers should control their timeouts by calling with the appropriate context.
Enforcing a fixed timeout can get in the way of expensive queries and migrations.
> Remove pipeline request 60s timeout
